<h1 style="color:#2192f1" align="center"> MULTI CLASS CLASSIFICATION</h1>


<h2 align="center" style="color:#f0e912">IMPORT LIBRARIES</h2>


In [49]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from LogisticRegression.src.multi_class_classification import *

<h2 align="center" style="color:#f0e912">DATA EXPLORATION</h2>


In [50]:
df = pd.read_csv("../data/multi_class_classification_dataset/dermatology.csv")

In [51]:
df.head()

erythema  scaling  definite_borders  itching  koebner_phenomenon  \
0         2        2                 0        3                   0   
1         3        3                 3        2                   1   
2         2        1                 2        3                   1   
3         2        2                 2        0                   0   
4         2        3                 2        2                   2   

   polygonal_papules  follicular_papules  oral_mucosal_involvement  \
0                  0                   0                         0   
1                  0                   0                         0   
2                  3                   0                         3   
3                  0                   0                         0   
4                  2                   0                         2   

   knee_and_elbow_involvement  scalp_involvement  ...  \
0                           1                  0  ...   
1                           1                  1  ...   
2                           0                  0  ...   
3                           3                  2  ...   
4                           0                  0  ...   

   disappearance_granular_layer  vacuolisation_damage_basal_layer  spongiosis  \
0                             0                                 0           3   
1                             0                                 0           0   
2                             0                                 2           3   
3                             3                                 0           0   
4                             2                                 3           2   

   saw_tooth_appearance_retes  follicular_horn_plug  \
0                           0                     0   
1                           0                     0   
2                           2                     0   
3                           0                     0   
4                           3                     0   

   perifollicular_parakeratosis  inflammatory_mononuclear_infiltrate  \
0                             0                                    1   
1                             0                                    1   
2                             0                                    2   
3                             0                                    3   
4                             0                                    2   

   band_like_infiltrate  age  class  
0                     0   55      2  
1                     0    8      1  
2                     3   26      3  
3                     0   40      1  
4                     3   45      3  

[5 rows x 35 columns]

In [52]:
df.describe()

erythema     scaling  definite_borders     itching  \
count  366.000000  366.000000        366.000000  366.000000   
mean     2.068306    1.795082          1.549180    1.366120   
std      0.664753    0.701527          0.907525    1.138299   
min      0.000000    0.000000          0.000000    0.000000   
25%      2.000000    1.000000          1.000000    0.000000   
50%      2.000000    2.000000          2.000000    1.000000   
75%      2.000000    2.000000          2.000000    2.000000   
max      3.000000    3.000000          3.000000    3.000000   

       koebner_phenomenon  polygonal_papules  follicular_papules  \
count          366.000000         366.000000          366.000000   
mean             0.633880           0.448087            0.166667   
std              0.908016           0.957327            0.570588   
min              0.000000           0.000000            0.000000   
25%              0.000000           0.000000            0.000000   
50%              0.000000           0.000000            0.000000   
75%              1.000000           0.000000            0.000000   
max              3.000000           3.000000            3.000000   

       oral_mucosal_involvement  knee_and_elbow_involvement  \
count                366.000000                  366.000000   
mean                   0.377049                    0.614754   
std                    0.834147                    0.982979   
min                    0.000000                    0.000000   
25%                    0.000000                    0.000000   
50%                    0.000000                    0.000000   
75%                    0.000000                    1.000000   
max                    3.000000                    3.000000   

       scalp_involvement  ...  focal_hypergranulosis  \
count         366.000000  ...             366.000000   
mean            0.519126  ...               0.393443   
std             0.905639  ...               0.849406   
min             0.000000  ...               0.000000   
25%             0.000000  ...               0.000000   
50%             0.000000  ...               0.000000   
75%             1.000000  ...               0.000000   
max             3.000000  ...               3.000000   

       disappearance_granular_layer  vacuolisation_damage_basal_layer  \
count                    366.000000                        366.000000   
mean                       0.464481                          0.456284   
std                        0.864899                          0.954873   
min                        0.000000                          0.000000   
25%                        0.000000                          0.000000   
50%                        0.000000                          0.000000   
75%                        1.000000                          0.000000   
max                        3.000000                          3.000000   

       spongiosis  saw_tooth_appearance_retes  follicular_horn_plug  \
count  366.000000                  366.000000            366.000000   
mean     0.953552                    0.453552              0.103825   
std      1.130172                    0.954744              0.450433   
min      0.000000                    0.000000              0.000000   
25%      0.000000                    0.000000              0.000000   
50%      0.000000                    0.000000              0.000000   
75%      2.000000                    0.000000              0.000000   
max      3.000000                    3.000000              3.000000   

       perifollicular_parakeratosis  inflammatory_mononuclear_infiltrate  \
count                    366.000000                           366.000000   
mean                       0.114754                             1.866120   
std                        0.488723                             0.726108   
min                        0.000000                             0.000000   
25%                        0.000000                             1.000000   
5

<h2 align="center" style="color:#f0e912">DATA PREPROCESSING</h2>


In [53]:
df["age"] = df["age"].apply(lambda x: int(x) if x.isdigit() else None)

In [54]:
df.dropna(inplace=True)

In [55]:
class_counts = df["class"].value_counts()
df["weights"] = df["class"].apply(lambda x: 1/class_counts[x])

In [56]:
df_train = df.sample(random_state=42, frac=0.7, weights="weights")
df_test = df.drop(df_train.index)
df.drop("weights", axis=1, inplace=True)

In [57]:
nb_classes = df["class"].value_counts().count()

<h3 align="center" style="color:#5F75BF">CLASS BALANCE CHECK</h3>


In [58]:
df["class"].value_counts()

class
1    111
3     71
2     60
5     48
4     48
6     20
Name: count, dtype: int64

In [59]:
df_train["class"].value_counts()

class
1    57
2    47
3    47
5    40
4    40
6    20
Name: count, dtype: int64

<h3 align="center" style="color:#5F75BF">ADD INTERCEPT TERM</h3>


In [60]:
# Transform features and target into numpy
X = df_train.drop("class", axis=1)
y = df_train["class"].values.reshape(-1, 1)
# Intercept feature
i_term = np.ones((len(X), 1))
# Add intercept feature in other features
X_intercept = np.concatenate((i_term, X), axis=1)

In [61]:
# Transform features and target into numpy
X_test = df_test.drop("class", axis=1)
y_test = df_test["class"].values.reshape(-1, 1)
# Intercept feature
i_term_test = np.ones((len(X_test), 1))
# Add intercept feature in other features
X_test_intercept = np.concatenate((i_term_test, X_test), axis=1)

<h2 align="center" style="color:#f0e912">TRAINING</h2>


In [62]:
theta_list = [np.zeros((X_intercept.shape[1], 1)) for _ in range(nb_classes)]

In [63]:
proba_class_i(X_intercept[0], theta_list, 1)

array([0.16666667])

In [64]:
X_intercept[8]

array([ 1.  ,  2.  ,  2.  ,  1.  ,  1.  ,  0.  ,  0.  ,  2.  ,  0.  ,
        2.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,
        1.  ,  1.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
        0.  ,  2.  ,  0.  ,  1.  ,  2.  ,  2.  ,  0.  , 10.  ,  0.05])

In [65]:
single_log_likelihood(X_intercept[8], theta_list, y[8].item())

array([1.79175947])

In [66]:
log_likelihood(X_intercept, y, theta_list)

array([449.73162678])

<h2 align="center" style="color:#f0e912">TESTING</h2>
